/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '20/08/15 16:18' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 20/08/15 16:18
 */
public class EelChecker {
    public boolean checkOld(String hangmanWord, String rudeWord) {

        StringBuilder rudeWordRegex = new StringBuilder();
        for( char rudeWordLetter : rudeWord.toCharArray() )
        {
            rudeWordRegex.append( ".*" + rudeWordLetter );
        }
        rudeWordRegex.append( ".*" );

        return hangmanWord.matches(rudeWordRegex.toString());
    }

    public boolean check(String hangmanWord, String rudeWord){
        return rudeWord.matches( hangmanWord.replaceAll("[^" + rudeWord + "]",""));
    }
}
