import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Alec.Tunbridge' at '20/08/15 16:18' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 20/08/15 16:18
 */
public class EelTest {

    private EelChecker checker;

    @Before
    public void setup(){
        checker = new EelChecker();
    }

    @Test
    public void shouldReturnFalseGivenNonMatchingInputs() {
        assertFalse(checker.check("one", "two"));
    }

    @Test
    public void shouldReturnTrueGivenMatchingInputs() {
        assertTrue(checker.check("one", "one"));
    }

    @Test
    public void shouldReturnTrueWhenRudeWordASubstring(){
        assertTrue(checker.check("ohsingleview", "singleview"));
    }

    @Test
    public void shouldNotContainRudeWordWithinHangmanWord(){
        assertTrue(checker.check("b_ad","bad"));
    }

    @Test
    public void shouldNotContainRudeWordWithDuplicateLettersWithinHangmanWord(){
        assertFalse(checker.check("baad", "bad"));
    }

    @Test
    public void acceptanceTest() {

        assertTrue(checker.check("synchronized", "snond"));
        assertTrue(checker.check("misfunctioned", "snond"));
        assertFalse(checker.check("mispronounced", "snond"));
        assertFalse(checker.check("shotgunned", "snond"));
        assertTrue(checker.check("snond", "snond"));
        assertFalse(checker.check("dab", "bad"));
        assertFalse(checker.check("badbad", "bad"));
    }
}
